# Learn the Basics
[PyTorch Tutorial Doc](https://docs.pytorch.org/tutorials/beginner/basics/intro.html)

In [ ]:
import torch
import numpy as np


In [ ]:
# initialize tensor from list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
# initialize tensor from np array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [ ]:
# initialize tensor from another tensor
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_zeros = torch.zeros_like(x_data)
print(f"Zeros Tensor: \n {x_zeros} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[0.4516, 0.9487],
        [0.3092, 0.1272]]) 



In [ ]:
# tensor of random and constant
shape = (2, 3, 5) # outer first to inner last
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[[0.9921, 0.8389, 0.5772, 0.1090, 0.0351],
         [0.9764, 0.5828, 0.5044, 0.5168, 0.3949],
         [0.8364, 0.8128, 0.3646, 0.2772, 0.6258]],

        [[0.0825, 0.7545, 0.7762, 0.1899, 0.0128],
         [0.1945, 0.4907, 0.6940, 0.8986, 0.9920],
         [0.2203, 0.8014, 0.7141, 0.2954, 0.1712]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]) 



In [ ]:
# tensor attributes
tensor = torch.rand(2,3,5)
print(f"Tensor Shape: {tensor.shape}")
print(f"Tensor Datatype: {tensor.dtype}")
print(f"Tensor is stored on device: {tensor.device}")

Tensor Shape: torch.Size([2, 3, 5])
Tensor Datatype: torch.float32
Tensor is stored on device: cpu


In [ ]:
# move the tensor to the current accelerator if available
print(f"tensor is on device: {tensor.device}")
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(f"tensor has been moved to device: {tensor.device}")


tensor is on device: cpu
tensor has been moved to device: mps:0


In [ ]:
# indexing and slicing like numpy
tensor = torch.ones(4, 4)
print(tensor)
tensor[0] = -1 # update first row
tensor[:, -1] = 0 # update last column
print(f"First row: {tensor[0]}")
print(f"Last column: {tensor[:, -1]}")
print(tensor)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([-1., -1., -1.,  0.])
Last column: tensor([0., 0., 0., 0.])
tensor([[-1., -1., -1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.]])


In [ ]:
# concatenate a sequence of tensors along a given dimension, 0 is the innerest
t0 = torch.cat([tensor, tensor, tensor], dim=0)
print(t0)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[-1., -1., -1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [-1., -1., -1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [-1., -1., -1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.]])
tensor([[-1., -1., -1.,  0., -1., -1., -1.,  0., -1., -1., -1.,  0.],
        [ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.]])


In [ ]:
# arithmetic operation - matrix multiplication
# y1, y2, y3 have the same value
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)
print(f"transpose of tensor: \n{tensor.T}")

y1 = tensor.T @ tensor
print(f"y1 = tensor.T @ tensor = \n{y1}")

y2 = tensor.T.matmul(tensor) # same as y2
print(f"y2 = tensor.T.matmul(tensor) = \n{y2}")

y3 = torch.rand_like(y1)
print(f"initiate y3 with the shape of y1: \n{y3}")
torch.matmul(tensor.T, tensor, out=y3)
print(f"calculate the multiplication and assign the output to y3: \n{y3}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
transpose of tensor: 
tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
y1 = tensor.T @ tensor = 
tensor([[4., 0., 4., 4.],
        [0., 0., 0., 0.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.]])
y2 = tensor.T.matmul(tensor) = 
tensor([[4., 0., 4., 4.],
        [0., 0., 0., 0.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.]])
initiate y3 with the shape of y1: 
tensor([[0.9939, 0.6490, 0.8507, 0.1899],
        [0.2876, 0.8715, 0.7515, 0.5969],
        [0.3648, 0.2004, 0.4021, 0.0503],
        [0.0694, 0.9324, 0.5475, 0.1287]])
calculate the multiplication and assign the output to y3: 
tensor([[4., 0., 4., 4.],
        [0., 0., 0., 0.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.]])


In [ ]:
# arithmetic operation - element-wise product (A * B = B * A)
# z1, z10, z2, z3 have the same value
z1 = tensor.T * tensor
z10 = tensor * tensor.T
z2 = tensor.mul(tensor.T)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor.T, out=z3)
print(z1)
print(z10)
print(z2)
print(z3)

tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# single-element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
# in-place operation
print(f"{tensor} \n")

print(f"{tensor + 5} \n")

print(tensor.add(5))
print(f"add without _: {tensor} \n")

tensor.add_(5)
print(f"add_: {tensor} \n")


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
add without _: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

add_: tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [ ]:
# bridge with numpy
# tensors on CPU and numpy arrays can share their underlying memory locations, changing one will change the other.
print("tensor to numpy")
t = torch.ones(2, 3)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

print("\nnumpy to tensor")
n = np.ones([2, 3])
print(f"n = np.ones([2, 3]): \n{n}")
t = torch.from_numpy(n)
print(f"t = torch.from_numpy(n): \n{t}")
np.add(n, 1, out=n)
print(f"\nupdated n: np.add(n, 1, out=n)")
print(f"n: {n}")
print(f"t: {t}")


tensor to numpy
t: tensor([[1., 1., 1.],
        [1., 1., 1.]])
n: [[1. 1. 1.]
 [1. 1. 1.]]
t: tensor([[2., 2., 2.],
        [2., 2., 2.]])
n: [[2. 2. 2.]
 [2. 2. 2.]]

numpy to tensor
n = np.ones([2, 3]): 
[[1. 1. 1.]
 [1. 1. 1.]]
t = torch.from_numpy(n): 
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

updated n: np.add(n, 1, out=n)
n: [[2. 2. 2.]
 [2. 2. 2.]]
t: tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
