# Introduction to PyTorch
[PyTorch Beginner Series on YouTube](https://www.youtube.com/playlist?list=PL_lsbAsL_o2CTlGHgMxNrKhzP97BaG9ZN)

In [ ]:
import torch

## PyTorch Tensors

In [ ]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype) # default type is float32

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [ ]:
# specify dtype
z16 = torch.zeros(5, 3, dtype=torch.int16)
print(z16)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)


In [ ]:
# seed of rand
torch.manual_seed(1992)
r1 = torch.rand(5, 3)
r2 = torch.rand(5, 3)
print(r1)
print(r2)

torch.manual_seed(1992)
r3 = torch.rand(5, 3)
print(f"\nr3 {r3}\n= r1 {r1}")


tensor([[0.2065, 0.8209, 0.9006],
        [0.9611, 0.7832, 0.7027],
        [0.4265, 0.5869, 0.6678],
        [0.2548, 0.7745, 0.4713],
        [0.0950, 0.1665, 0.5943]])
tensor([[0.7621, 0.6171, 0.8944],
        [0.4382, 0.2336, 0.3888],
        [0.7425, 0.0427, 0.9232],
        [0.5066, 0.6515, 0.6728],
        [0.6081, 0.1511, 0.4682]])

r3 tensor([[0.2065, 0.8209, 0.9006],
        [0.9611, 0.7832, 0.7027],
        [0.4265, 0.5869, 0.6678],
        [0.2548, 0.7745, 0.4713],
        [0.0950, 0.1665, 0.5943]])
= r1 tensor([[0.2065, 0.8209, 0.9006],
        [0.9611, 0.7832, 0.7027],
        [0.4265, 0.5869, 0.6678],
        [0.2548, 0.7745, 0.4713],
        [0.0950, 0.1665, 0.5943]])


In [ ]:
# manipulation for mats in the same shape
ones = torch.ones(5, 3)
print(ones)

twos = torch.ones(5, 3) * 2
print(twos)

threes = ones + twos
print(threes)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [39]:
# available mathematical operations
torch.manual_seed(1992)
r = torch.rand(3, 3)
print(f"random numbers within (0, 1)\n{r}")

r = r*2 - 1
print(f"random numbers within (-1, 1)\nr = {r}")

print(f"absolute\n{r.abs()}")

print(f"asin\n{r.asin()}")

print(f"max\n{r.max()}")

print(f"average\n{r.mean()}")

print(f"standard deviation\n{r.std()}")

print(f"Determinant of r\n{r.det()}")

print(f"Singular value decomposition of r\n{r.svd()}")

random numbers within (0, 1)
tensor([[0.2065, 0.8209, 0.9006],
        [0.9611, 0.7832, 0.7027],
        [0.4265, 0.5869, 0.6678]])
random numbers within (-1, 1)
r = tensor([[-0.5869,  0.6419,  0.8013],
        [ 0.9221,  0.5664,  0.4055],
        [-0.1471,  0.1739,  0.3357]])
absolute
tensor([[0.5869, 0.6419, 0.8013],
        [0.9221, 0.5664, 0.4055],
        [0.1471, 0.1739, 0.3357]])
asin
tensor([[-0.6273,  0.6969,  0.9294],
        [ 1.1736,  0.6021,  0.4175],
        [-0.1476,  0.1747,  0.3423]])
max
0.9221391677856445
average
0.34585320949554443
standard deviation
0.47724148631095886
Determinant of r
-0.11197712272405624
Singular value decomposition of r
torch.return_types.svd(
U=tensor([[-0.8269,  0.4663, -0.3143],
        [-0.4805, -0.8762, -0.0358],
        [-0.2921,  0.1214,  0.9486]]),
S=tensor([1.2841, 1.1151, 0.0782]),
V=tensor([[ 0.0663, -0.9861,  0.1526],
        [-0.6648, -0.1577, -0.7302],
        [-0.7441,  0.0530,  0.6660]]))


## PyTorch Models

In [ ]:
import torch.nn as nn           # the parent object of PyTorch models
import torch.nn.functional as F # the activation function